# Generated by Django 5.0.6 on 2024-06-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        #migrations.AlterField(
        #    model_name='book',
        #    name='id',
        #    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        #),
    ]
