# Generated by Django 4.1.13 on 2024-07-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_image_url_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='old_price',
            field=models.FloatField(blank=True, null=True),
        ),
        #migrations.AlterField(
        #    model_name='category',
        #    name='name',
        #    field=models.CharField(max_length=100),
        #),
    ]
