from django import template

register = template.Library()

CATEGORY_MAP = {
    'autoajuda': 'Autoajuda',
    'culinaria-e-gastronomia': 'Culinária & Gastronomia',
    'direito': 'Direito',
    'educacao': 'Educação',
    'ficcao': 'Ficção',
    'ficcao-infantil': 'Ficção Infantil',
    'ficcao-juvenil': 'Ficção Juvenil',
    'negocios-e-economia': 'Negócios & Economia',
    'quadrinhos-mangas-e-graphic-novels': 'Quadrinhos, Mangás & Graphic Novels',
    'religiao': 'Religião',
    'animais-de-estimacao': 'Animais De Estimação',
    'antiguidades-e-colecionaveis': 'Antiguidades & Colecionáveis',
    'apoio-aos-estudos': 'Apoio Aos Estudos',
    'arquitetura': 'Arquitetura',
    'arte': 'Arte',
    'artes-performaticas': 'Artes Performáticas',
    'artesanato-e-estilo-de-vida': 'Artesanato & Estilo De Vida',
    'biblias': 'Bíblias',
    'biografia-e-autobiografia': 'Biografia & Autobiografia',
    'casa-e-lar': 'Casa & Lar',
    'ciencia': 'Ciência',
    'ciencia-politica': 'Ciência Política',
    'ciencias-sociais': 'Ciências Sociais',
    'colecoes-literarias': 'Coleções Literárias',
    'computacao-e-informatica': 'Computação & Informática',
    'corpo-mente-e-espirito': 'Corpo, Mente & Espírito',
    'crimes': 'Crimes',
    'critica-literaria': 'Crítica Literária',
    'design': 'Design',
    'engenharia-e-tecnologia': 'Engenharia & Tecnologia',
    'esporte-e-lazer': 'Esporte & Lazer',
    'estudo-de-linguas-estrangeiras': 'Estudo De Línguas Estrangeiras',
    'familia-e-relacionamentos': 'Família & Relacionamentos',
    'filosofia': 'Filosofia',
    'fotografia': 'Fotografia',
    'historia': 'História',
    'humor': 'Humor',
    'jardinagem': 'Jardinagem',
    'jogos-e-atividades': 'Jogos & Atividades',
    'lingua-comunicacao-e-disciplinas-relacionadas': 'Língua, Comunicação & Disciplinas Relacionadas',
    'livros-musica': 'Livros Música',
    'matematica': 'Matemática',
    'medicina': 'Medicina',
    'nao-ficcao-infantil': 'Não Ficção Infantil',
    'nao-ficcao-juvenil': 'Não Ficção Juvenil',
    'natureza': 'Natureza',
    'poesia': 'Poesia',
    'psicologia': 'Psicologia',
    'referencia': 'Referência',
    'saude-e-boa-forma': 'Saúde & Boa Forma',
    'teatro': 'Teatro',
    'transportes': 'Transportes',
    'viagem': 'Viagem',
}

@register.filter
def pretty_category(category):
    return CATEGORY_MAP.get(category, category)
